### ISSUE TITLE
Linux/Windows rebuild fail

### ISSUE THREAD

**Issue by justnajm** [bazzisoft-openfl-extensions/camera#1]
Hi,
Thanks for this very important extention :)
I am having following errors on my laptop ubuntu 14 LTS, android success but not linux/windows
    lime rebuild extensionkit linux
Error: In file included from /usr/include/stdint.h:25:0,
                 from /usr/lib/gcc/x86_64-linux-gnu/4.8/include/stdint.h:9,
                 from /usr/lib/haxe/lib/hxcpp/3,1,68/include/hx/OS.h:61,
                 from /usr/lib/haxe/lib/hxcpp/3,1,68/include/hx/CFFI.h:4,
                 from ./common/ExternalInterface.cpp:9:
/usr/include/features.h:374:25: fatal error: sys/cdefs.h: No such file or directory
 #  include <sys/cdefs.h>
                         ^
compilation terminated.

```
lime rebuild camera linux
```

Error: In file included from /usr/include/stdio.h:27:0,
                 from ./common/Camera.cpp:1:
/usr/include/features.h:374:25: fatal error: sys/cdefs.h: No such file or directory
 #  include <sys/cdefs.h>
                         ^
compilation terminated.

**Comment by bazzisoft** [comment]
Sorry I missed the notification for this issue somehow. 

The extension doesn't do anything for linux/windows, I think the C++ code just has a stub function that returns a failure code. 

That being said, it should compile - it compiles for me no problem in Windows anyway, I haven't tried in linux.

What versions of Haxe and OpenFL are you running?
