### ISSUE TITLE
Could not compile !

### ISSUE THREAD

**Issue by saumya** [bazzisoft-openfl-extensions/camera#3]
Error is saying this.

`camera/src/org/haxe/extension/camera/Camera.java:6: error: package org.haxe.extension.extensionkit does not exist`

**Comment by bazzisoft** [comment]
Hi @saumya, seems you are missing the "extensionkit" dependency. Please follow the instructions in the README closely:

https://github.com/bazzisoft-openfl-extensions/camera/blob/master/README.md

**Comment by saumya** [comment]
Thanks for the reply.

Have included the extension as suggested. But still same error. Any extra step to compile ?

Can not be closed ! the issue it still open.

**Comment by saumya** [comment]
@bazzisoft can you confirm and open the issue again.

**Comment by bazzisoft** [comment]
Hmmm... in this case I don't have a good answer for you. If the "extensionkit" is present in the correct directory, I'm not sure why the Java compiler isn't finding the file. I suggest you check the Java source paths in the generated build files and try to understand if the extensionkit sources are in the wrong place, or a suitable path entry is missing from the Java compiler source paths.

**Comment by saumya** [comment]
thanks @bazzisoft

Here is my setup
-  both the libraries are present in their respective folders "camera" and "extensionkit"
- both of them are inside one folder, side by side

Then I run the commands

```
lime rebuild extensionkit android
lime rebuild camera android
```

Till now everything is fine.

Now in my project, I have added

```
<include path="/Users/saumya/1_openfl/w_openfl_extensions/camera" />
```

And then compiling the project with 

```
lime test android
```

Are there any other steps involved ? Is there a problem because of the new android build system Gradle vs the old one ANT ?!

**Comment by bazzisoft** [comment]
Just a wild guess which probably won't work, but can you try a relative path with your <include> directive?

Failing that, it may well be the new build system. I haven't done any Haxe/Android for well over a year now, so I'm out of touch with the build systems and any changes to the APIs which may have occurred.

**Comment by saumya** [comment]
Whoa ! thanks, this is nice.

With relative path it went past my hurdle to the [next one, as mentioned in this issue](https://github.com/bazzisoft-openfl-extensions/camera/issues/2).

For clarification my lib path is as below now

```
<include path="../w_openfl_extensions/camera" />
```

Time to fix the other one :)

**Comment by bazzisoft** [comment]
Leaving this open: Update README to indicate relative paths for <include> directives.

**Comment by bazzisoft** [comment]
@player-03 Thanks for the fix. I'm closing this issue for now, please reopen if the issue persists.
